exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
    args: ['--markdown-linebreak-ext=md']
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: check-executables-have-shebangs
  - id: debug-statements
  - id: end-of-file-fixer
  - id: pretty-format-json
    args: ['--autofix', '--indent=4', '--no-sort-keys']
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']
  - id: no-commit-to-branch
    args: [--branch, main-priv, --branch, main]

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    language_version: python3
    args: [
      "--force-exclude=docs/conf.py"
    ]

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        files: "^src/"
        args: [--config-file=mypy.ini]
